[package]
name = "agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
agent-ebpf-common.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
dashmap.workspace = true
event-model.workspace = true
futures.workspace = true
hex.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
protocol.workspace = true
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
aya.workspace = true

[lints]
workspace = true
