apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "okoscope-agent.fullname" . }}
  labels:
    {{- include "okoscope-agent.labels" . | nindent 4 }}
data:
  agent.yaml: |
    apiVersion: okoscope.io/v1alpha1
    kind: AgentConfiguration
    server:
      endpoint: {{ .Values.server.endpoint | quote }}
      developmentPlaintext: {{ .Values.server.developmentPlaintext }}
      {{- if .Values.server.caSecret.name }}
      caFile: /var/run/secrets/okoscope-ca/{{ .Values.server.caSecret.key }}
      {{- end }}
    identity:
      nodeName: overridden-by-downward-api
      clusterName: {{ .Values.identity.clusterName | quote }}
    scope:
      workloads:
      {{- range $index, $mapping := .Values.workloads }}
        - applicationCredentialFile: /var/run/secrets/okoscope/applications/{{ $index }}
          namespace: {{ $mapping.namespace | quote }}
          kind: {{ $mapping.kind | quote }}
          name: {{ default "*" $mapping.name | quote }}
          {{- with $mapping.labels }}
          labels: {{ toJson . }}
          {{- end }}
      {{- end }}
    observation:
{{ toYaml .Values.observation | indent 6 }}
    safety:
{{ toYaml .Values.safety | indent 6 }}
