apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: okoscope
resources:
  - server.yaml
  - web.yaml
  - agent-rbac.yaml
  - agent-config.yaml
  - agent.yaml
  - disruption.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: okoscope
    includeSelectors: false
    includeTemplates: true
