{{- if not .Values.internalSecret.existingSecret }}
{{- $name := include "okoscope.internalSecret" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "okoscope.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.internalSecret.adminCredentialKey }}: {{ if $existing }}{{ index $existing.data .Values.internalSecret.adminCredentialKey }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
  {{ .Values.internalSecret.webhookEncryptionKey }}: {{ if $existing }}{{ index $existing.data .Values.internalSecret.webhookEncryptionKey }}{{ else }}{{ randAlphaNum 64 | sha256sum | b64enc }}{{ end }}
  {{ .Values.internalSecret.identityTokenKey }}: {{ if $existing }}{{ index $existing.data .Values.internalSecret.identityTokenKey }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
  {{ .Values.internalSecret.mailEncryptionKey }}: {{ if and $existing (hasKey $existing.data .Values.internalSecret.mailEncryptionKey) }}{{ index $existing.data .Values.internalSecret.mailEncryptionKey }}{{ else }}{{ randAlphaNum 64 | sha256sum | b64enc }}{{ end }}
{{- end }}
