{{- if not .Values.setupAuthorization.existingSecret }}
{{- $name := printf "%s-setup" (include "okoscope.fullname" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "okoscope.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.setupAuthorization.tokenKey }}: {{ if $existing }}{{ index $existing.data .Values.setupAuthorization.tokenKey }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
{{- end }}
