apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: okoscope
resources:
  - rbac.yaml
  - config.yaml
  - daemonset.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: okoscope
    includeSelectors: false
    includeTemplates: true
