apiVersion: v1
kind: ServiceAccount
metadata:
  name: okoscope-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: okoscope-agent
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    resourceNames: [kube-system]
    verbs: [get]
  - apiGroups: [apps]
    resources: [replicasets, deployments]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: okoscope-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: okoscope-agent
subjects:
  - kind: ServiceAccount
    name: okoscope-agent
    namespace: okoscope
